name: Belisarius Update on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy to Server"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$BELISARIUS_SSH_KEY" > ~/.ssh/belisarius.key
          chmod 600 ~/.ssh/belisarius.key
          ssh-keyscan -p 2310 $BELISARIUS_IP >> ~/.ssh/known_hosts
          echo "Host belisarius
            HostName $BELISARIUS_IP
            User $BELISARIUS_USER
            Port 2310
            IdentityFile ~/.ssh/belisarius.key" > ~/.ssh/config
        env:
          BELISARIUS_SSH_KEY: ${{ secrets.BELISARIUS_SSH_KEY }}
          BELISARIUS_IP: ${{ secrets.BELISARIUS_IP }}
          BELISARIUS_USER: ${{ secrets.BELISARIUS_USER }}

      - name: Fetch and Reset and Update
        run: |
          ssh belisarius <<EOF
          set -e
          # Update the repository
          cd /home/phillip/GitHub/circus-factions-builder
          git fetch --all && git reset --hard origin/main && git clean -fd
          # Activate and update the Python virtual environment
          source /home/phillip/GitHub/circus-factions-builder/.venv/bin/activate
          pip install -r requirements.txt
          deactivate
          # Activate and update the Node environment; yes, the beginning part is needed
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use
          npm install
          EOF
